# Generated by Django 4.0.2 on 2022-02-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VokabelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vokabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('german', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('vokabel_sets', models.ManyToManyField(related_name='vokabeln', to='vokabeltrainer.VokabelSet')),
            ],
        ),
    ]
