# Generated by Django 4.0.2 on 2022-02-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabeltrainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vokabel',
            name='vokabel_sets',
            field=models.ManyToManyField(blank=True, null=True, related_name='vokabeln', to='vokabeltrainer.VokabelSet'),
        ),
    ]
