# Generated by Django 4.0.2 on 2022-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabeltrainer', '0002_alter_vokabel_vokabel_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='vokabel',
            name='example_sentences',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vokabel',
            name='english_description',
            field=models.TextField(default=''),
        ),
    ]
