# Generated by Django 4.0.2 on 2022-02-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabeltrainer', '0003_vokabel_example_sentences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobUndAufmunterung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LO', 'Lob für richtiges Ergebnis'), ('AU', 'Aufmunterung bei falschem Ergebnis')], default='LO', max_length=2)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
