# Generated by Django 4.0.2 on 2022-02-24 08:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabeltrainer', '0005_alter_vokabel_english_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vokabel',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vokabel',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lobundaufmunterung',
            name='text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
