# Generated by Django 4.0.2 on 2022-02-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vokabeltrainer', '0006_vokabel_correct_answers_vokabel_wrong_answers_and_more'),
        ('vokabeltrainer', '0007_vokabel_correct_answers_vokabel_wrong_answers'),
    ]

    operations = [
    ]
