# Generated by Django 4.0.2 on 2022-02-26 10:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabeltrainer', '0008_merge_20220226_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='InFormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('formal', models.CharField(max_length=255)),
                ('informal', models.CharField(max_length=255)),
                ('example_informal', tinymce.models.HTMLField(default='')),
                ('example_formal', tinymce.models.HTMLField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
