# Generated by Django 4.0.2 on 2022-02-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vokabeltrainer', '0009_informal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informal',
            old_name='example_formal',
            new_name='hint_formal',
        ),
        migrations.RenameField(
            model_name='informal',
            old_name='example_informal',
            new_name='hint_informal',
        ),
    ]
